### ISSUE TITLE
Formalizing TypeScript dependency

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-automation-harness#3]
[In an effort to maintain parity with the ARIA-AT projects](https://github.com/bocoup/aria-at-automation-harness/pull/2/files#r774754948), this project uses JavaScript rather than TypeScript. Because we recognize the benefit of static typing, we have been annotating the JavaScript source code with specially-formatted comments which contain that information. Some of us have configured our development environments to consume those annotations and inform us of problems.

We'd like to formalize the dependency so that future contributors can benefit from the extra information, be informed of mistakes, and help us preserve it. We're not currently interested in writing TypeScript code in this repository. For now, we want to extend the project documentation and contribution workflow to acknowledge the structured JavaScript comment system that's already in use.

Do folks agree that the current state of affairs is unideal? Do you think that it would be disruptive for future contributors to find the more strict conventions in this project, even if we make those documentation and workflow improvements?

**Comment by zcorpan** [comment]
Is this convention lintable?

**Comment by jugglinmike** [comment]
Yup: machine-powered validation is the workflow extension I have in mind.

**Comment by mzgoddard** [comment]
https://github.com/w3c/aria-at-automation-driver/pull/38 is an example of some of the work that can be done under formalizing a typescript dependency in this repo and other related aria-at repos. (Wanted to put a link between this issue and that PR for historical use.)
