### ISSUE TITLE
Expose 'mode switch timeout' as a command-line argument

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-automation-harness#49]
The harness's logic for change the "mode" of the NVDA screen reader includes a timeout. As of this writing, the timeout value is hard-coded to [a value which was experimentally derived based on the experience of a single contributor in the context of their own development machine](https://github.com/w3c/aria-at-automation-harness/pull/48#discussion_r1543556920). Because the optimal value is expected to vary from environment to environment, it should be possible for the operator to specify it when running the harness. In other words: it should be controlled by a command-line argument.

**Comment by gnarf** [comment]
It might be nice to also allow configuring the other delays —- for instance my VM on my local testing setup needs a longer AFTER_NAVIGATION_DELAY
