### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-automation-harness#59]
This project's automated tests do not currently include static analysis of the source code. Extend the tests with validation performed by a tool like ESLint.

**Comment by gnarf** [comment]
I think there is a pre-commit running these currently but yeah, worth the extra check on CI

**Comment by jugglinmike** [comment]
I'd like something stronger than [code-style enforcement](https://github.com/w3c/aria-at-automation-harness/blob/21230f6531b21bbde2794f56e29912ef93dab182/package.json#L38).

**Comment by jugglinmike** [comment]
I'm re-opening this issue because contrary to GitHub's inference, gh-63 did not resolve this.
