### ISSUE TITLE
Unconventional globbing behavior

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-automation-harness#9]
This project includes a pattern matching engine for selecting files. It's referred to as "globbing" because it's modeled on the "globing" syntax implemented in many other programming environments. While using the software, I found a number of cases where the behavior does not match convention. I'll summarize here and demonstrate convention with examples from [GNU Bash](https://www.gnu.org/software/bash/) and [Node.js minimatch](https://www.npmjs.com/package/minimatch).

In this project's implementation, the start character (`*`) matches one or more characters (there's no test for this behavior).

Conventionally, it matches zero or more characters:

    $ touch hello h_ello
    $ ls h*ello
    hello  h_ello

    > minimatch('hello', 'h*ello')
    true
    > minimatch('h_ello', 'h*ello')
    true

In this project's implementation, the comma character behaves as a logical "or" wherever it appears:

    assertGlobTrue('a,b', 'a');
    assertGlobTrue('a,b', 'b');
    assertGlobTrue('{a,b}', 'a');
    assertGlobTrue('{a,b}', 'b');

Conventionally, `,` matches only the literal comma character, with the "option" behavior limited to applications within braces:

    $ touch a b a,b
    $ ls a,b
    a,b
    $ ls {a,b}
    a  b

    > minimatch('a', 'a,b'));
    false
    > minimatch('b', 'a,b'));
    false
    > minimatch('a,b', 'a,b'));
    true
    > minimatch('a', '{a,b}'));
    true
    > minimatch('b', '{a,b}'));
    true
    > minimatch('a,b', '{a,b}'));
    false

In this project's implementation, the solidus is interpreted as both a literal forward slash character and a delimiter for partial matching:

    assertGlobTrue('a/b', 'a');
    assertGlobTrue('a/b', 'a/');
    assertGlobTrue('a/b', 'a/b');

Conventionally, `/` only functions as a literal forward slash:

    $ mkdir a; touch a/b
    $ ls a/b
    a/b

    > minimatch('a', 'a/b')
    false
    > minimatch('a/', 'a/b')
    false
    > minimatch('a/b', 'a/b')
    true

We could probably extend the current implementation to address these cases, but that will further complicate a component of the system which is only orthogonally related to the problem domain. I'm also not convinced that this report is exhaustive, so there may be still other unconventional behaviors present. In the interest of reducing complexity and minimizing surprise, I'd like to revisit my earlier suggestion to use an external project.

**Comment by gnarf** [comment]
> Conventionally, `,` matches only the literal comma character, with the "option" behavior limited to applications within braces:

I think we might want to keep this particular behavior around, effectively treating the whole thing as if it were within curlies when an unescaped comma is correct.  It reads as "comma separated list of globs" without the (`{}`) on the command line, and was the least confusing aspect. The command we are using with the automation currently relies on this "hidden brace":

```
env:
  ARIA_AT_WORK_DIR: ${{ inputs.work_dir || 'tests/alert' }}
  ARIA_AT_TEST_PATTERN: ${{ inputs.test_pattern || 'reference/**,test-*-nvda.*'}}
```
and the command args
```
--plan-workingdir aria-at/build/$env:ARIA_AT_WORK_DIR $env:ARIA_AT_TEST_PATTERN
```

**Comment by gnarf** [comment]
> We could probably extend the current implementation to address these cases, but that will further complicate a component of the system which is only orthogonally related to the problem domain. I'm also not convinced that this report is exhaustive, so there may be still other unconventional behaviors present. In the interest of reducing complexity and minimizing surprise, I'd like to revisit my earlier suggestion to use an external project.

I agree, looks like minimatch even has `.makeRe()` so it should be an easy swap, opinion on the "implied curlies when comma" interpretation on my last message?  Or do we want to fix this now and have a breaking issue with all of our scripts?

**Comment by jugglinmike** [comment]
Let's fix the call sites, too
